Provide msp-sdk to allow the use of annotation interception functions
erda-project/erda-java-agent pull request #15
Opened 2021-05-27 03:50 UTC by liuhaoyang

2021-05-27 13:01 UTC, innerpeacez requested changes

2021-05-27 13:01 UTC, innerpeacez commented on agent-sdk/pom.xml
> +
Missing <version>

2021-05-28 06:31 UTC, liuhaoyang commented on agent-sdk/pom.xml
> +
use parent's version

2021-05-28 06:46 UTC, innerpeacez approved these changes

2021-05-28 06:46 UTC, merged